# Generated by Django 3.2.3 on 2021-06-01 17:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('tittle', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Название')),
                ('location', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.CharField(max_length=50, verbose_name='Описание')),
                ('photos', models.CharField(max_length=50, verbose_name='Фотографии')),
                ('location', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.country')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=50, verbose_name='Название')),
                ('location', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.country')),
            ],
            options={
                'verbose_name': 'Столица',
                'verbose_name_plural': 'Столицы',
            },
        ),
    ]
